name: 'pub-dashboard'
description: 'Package dashboard table'
author: 'AmosHuKe'
branding:
  icon: activity
  color: blue
inputs:
  github_token:
    description: 'Github Token with repo permissions'
    required: true
  github_repo:
    description: 'Github repo to be manipulated'
    required: true
  filename:
    description: 'Filename in Github repo'
    required: false
    default: README.md
  publisher_list:
    description: 'e.g fluttercandies.com,bb,cc'
    required: false
  package_list:
    description: 'e.g flutter_tilt,bb,cc'
    required: false
  sort_field:
    description: 'name | published'
    required: false
    default: name
  sort_mode:
    description: 'asc | desc'
    required: false
    default: asc
runs:
  using: 'composite'
  steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Clone action & repo
      run: |
        tempActionPath="temp/action/github.com/AmosHuKe/pub-dashboard"
        git clone https://github.com/AmosHuKe/pub-dashboard $tempActionPath
        git clone ${{ inputs.github_repo }} $tempActionPath/repo
        cd $tempActionPath
      shell: bash

    - name: Setup Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version-file: temp/action/github.com/AmosHuKe/pub-dashboard/go.mod
        cache: false
      id: go
    
    - name: Update Markdown
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        go run main.go -filename repo/${{ inputs.filename }} -publisherList ${{ inputs.publisher_list }} -packageList ${{ inputs.package_list }} -sortField ${{ inputs.sort_field }} -sortMode ${{ inputs.sort_mode }}
        cd temp/action/github.com/AmosHuKe/pub-dashboard/repo
        gh auth setup-git -h github.com
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -a -m "docs(pub-dashboard): pub-dashboard has updated readme"
        git push
      shell: bash